#!/usr/bin/env bash
# This script is displaying content of the file /etc/passwd#using the while loop + IFS.

while IFS=':' read -r username uid homedir shell passwd info < /etc/passwd; do
  echo "The user $username is part of the $uid gang, lives in $homedir and rides $shell."
  echo "USER ID's place is protected by the passcode $passwd, more info about the user here: $info"
done

