#!/usr/bin/env bash
# This script is displaying groups visitors by IP and HTTP
# Assuming your Apache access log file is named "access.log

awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn

