#!/usr/bin/env bash
#this script displays bad luck for the 4th loop iteration
displays good luck at the 8th loop iteration
displays Best School at the other iterations

while [ $i -le 10 ]; do
  if [ $i -eq 4 ]; then
    echo "Bad luck"
  elif [ $i -eq 8 ]; then
    echo "Good luck"
  else
    echo "Best School"
  fi
done

