#!/usr/bin/env bash
#this script displays bad luck for the 4th loop iteration

var1="Best School "
var2="bad luck"
var3="good luck"
i=0
while [ $i -lt 10 ]; do
  if [ $i -eq 3 ]; then
    echo "$var2"
  elif [ $i -eq 8 ]; then
    echo "$var3"
  else
    echo "$var1"
  fi
  i=$((i+1))
done
