#!/usr/bin/env bash
# This script is displaying the time for 12 hours, 59min

var="Hour"
h="0"
while [ $h -lt 13 ]; do
	echo "$var:" "$h"
	m="1"
	while [ $m -lt 60 ]; do
		echo "$m"
		((m++))
done
((h++))
done

