#!/usr/bin/env bash
#Bash script that displays the PID, along with the processv#name, of processes whose name contain the word bash

bash_pid=$(pgrep -l "bash")
script_pid=$(pgrep -l "3-show_your_bash_pid_made_easy")

echo "bash PID is $bash_pid and that the 3-show_your_bash_pid_made_easy script PID is $script_pid"

